# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Get evaluations

on:
#   push:
#     branches: [ "main" ]
  schedule:
    - cron: '00 10 * * 0,3,4,6'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.6.0]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Installing dependencies
      run: npm ci

    - name: Execute getEvaluations
      env:
        BASIC: ${{ secrets.BASIC }}
        COURSES: ${{ secrets.COURSES }}
        MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
        totalRequest: 600
      run: node getEvaluations.js
